# Generated by Django 3.1.6 on 2021-02-25 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('phNo', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipCode', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuideServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.BigIntegerField()),
                ('verification', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuideService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('service_area', models.ManyToManyField(to='accounts.GuideServiceArea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guideservice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GovId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govIdType', models.CharField(choices=[('PAN', 'PAN'), ('ADHAR', 'ADHAR')], max_length=10)),
                ('govIdNo', models.CharField(max_length=20)),
                ('govIdImage', models.ImageField(upload_to='GovermentId_Proof')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userGov', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyName', models.CharField(max_length=50)),
                ('agency_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('agency_Id', models.CharField(max_length=50)),
                ('agencyPhNo', models.BigIntegerField()),
                ('agencyCountry', models.CharField(max_length=25)),
                ('agencyCity', models.CharField(max_length=20)),
                ('agencyState', models.CharField(max_length=20)),
                ('agencyZipCode', models.BigIntegerField()),
                ('govApproved', models.BooleanField(default=False)),
                ('govApprovedId', models.CharField(blank=True, max_length=20, null=True)),
                ('agencyAddress', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('travmaks_partner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userAgency', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_access', models.BooleanField(default=False)),
                ('agency_access', models.BooleanField(default=False)),
                ('guide_access', models.BooleanField(default=False)),
                ('userId', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('agentId', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('guideId', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userAccess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
