# Generated by Django 3.1.6 on 2021-02-25 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_people', models.IntegerField(default=30)),
                ('tourId', models.CharField(max_length=30, unique=True)),
                ('tourHeading', models.CharField(max_length=1000)),
                ('tourSlug', models.CharField(max_length=255, unique=True)),
                ('startingLocation', models.CharField(max_length=300)),
                ('endLocation', models.CharField(max_length=300)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('description', models.TextField()),
                ('overview', models.TextField(blank=True, null=True)),
                ('inclusive', models.TextField()),
                ('exclusive', models.TextField()),
                ('highlight', models.TextField()),
                ('price', models.FloatField()),
                ('tour_type', models.CharField(choices=[('Family-Special', 'Family-Special'), ('Friends-Special', 'Friends-Special'), ('Couple-Friendly', 'Couple-Friendly'), ('Solo-Tour', 'Solo-Tour'), ('All', 'All')], max_length=50)),
                ('special_tour_type', models.CharField(choices=[('Bike-tours', 'Bike-tours'), ('Self-drive', 'Self-drive'), ('Trecking-Special', 'Trecking-Special'), ('None', 'None')], default='None', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='TourAccountThumbnail')),
                ('last_booking_date', models.DateField()),
                ('specialOffer', models.BooleanField(default=False)),
                ('specialOfferDescription', models.TextField(blank=True, null=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('othersThings', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('publish_mode', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourAgency', to='accounts.agencydetail')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=500)),
                ('query', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourQuery', to='travelagency.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='TourPreview')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='TourPreview')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelagency.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='travelagency.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
